import React from "react";
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="brand-div">
          <h1>wita</h1>
        </div>
        <div className="cart-login">
          <h1>cart</h1>
          <h1>login</h1>
        </div>
      </header>
      <main>{children}</main>
      <footer>footer</footer>
    </>
  );
}
